### ISSUE TITLE
Typo's walkthrough vision

### ISSUE THREAD

**Issue by maartenaelvoet** [raymon-ai/raymon#103]
use-case-description
- get some metadata for this request like the age of the patient, the hospital that generated the data, the machine id that generated the data. > Capital G 

integrating-raymon
- is set to the default one (ttps://api.raymon.ai/v0), > https 

monitoring-data-and-performance
- The model profile will build the extractors if necessary  (li > double space
- generated by a human-en-the-loop > human-in-the-loop

**Comment by kvhooreb** [comment]
> The model profile will build the extractors if necessary (li > double space
Cant find that one. Maybe it's already fixed? Others should be fixed now.
